version: "3.8"

services:
  t-glass:
    image: python:3.10-slim
    container_name: tglass

    restart: unless-stopped

    command: >
      sh -c "
      pip install --no-cache-dir aiohttp requests python-dotenv &&
      python /app/t-glass.py
      "

    volumes:
      - ./:/app

    ports:
      - "19944:80"

    environment:
      PYTHONUNBUFFERED: "1"
      TRADERNET_TICKER: T
