version: '3.8'

services:
  t-glass:
    image: python:3.10-slim
    container_name: t-glass
    restart: unless-stopped
    
      
    volumes:
      - ./data:/data
      - ./logs:/data/logs
    
    working_dir: /
    
    environment:
      - TRADERNET_PUBLIC_KEY=${TRADERNET_PUBLIC_KEY}
      - TRADERNET_PRIVATE_KEY=${TRADERNET_PRIVATE_KEY}
      - TRADERNET_TICKER=TECHSMART
      - MAX_BOT_TOKEN=${MAX_BOT_TOKEN}
      - MAX_CHAT_ID=${MAX_CHAT_ID}
      - VSEGPT_API_KEY=${VSEGPT_API_KEY}
      - PYTHONUNBUFFERED=1
    
    command: >
      sh -c "
        apt-get update && apt-get install -y curl &&
        pip install --no-cache-dir requests aiohttp python-dotenv &&
        python t-glass.py
      "